FROM python:3

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/src
COPY src/Session.py ./
COPY src/sessGen.py ./
COPY src/weighteddice.py ./

WORKDIR /usr

CMD [ "python", "./src/sessGen.py" ]