

version: "3"
services:
  mqtt:
      image: toke/mosquitto
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped

  redis:
      image: redis
      container_name: redis
      expose:
        - 6379
      ports:
        - 6379:6379

  web:
    build: FrontEnd/.
    container_name: web-front-end
    environment:
      - REDIS_IP_ADDRESS=redis
    ports:
      - "9002:80"
    depends_on:
      - redis

  datahighway:
    build: DataHighway/.
    container_name: datahighway
    environment:
      - REDIS_IP_ADDRESS=redis
      - MQTT_IP_ADDRESS=mqtt
    depends_on:
      - redis
      - mqtt

  session_gen:
    build: SessionGen/.
    container_name: session_gen
    environment:
      - REDIS_IP_ADDRESS=redis
      - OUTPUT_TO=REDIS_DB
    depends_on:
      - redis

  redis-commander:
    build: Redis-cmdr/.
    container_name: redis-commander
    links:
      - redis
    ports:
      - "9004:8081"
    command: --port 8081 --redis-host redis

  jupyter:
    #image: jupyter/all-spark-notebook:python-3.9.4
    image: jupyter/datascience-notebook:python-3.9.4
    volumes:
      - "./DataAnalysis:/home/jovyan/work:rw"
      - "./DataAnalysis/DONT_CHANGE_FIXES_PASSWORDS:/etc/jupyter:rw"
    ports:
      - "9003:8888"
    environment:
      - PASSWORD=guest
      - REDIS_IP_ADDRESS=redis
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
    - redis
